repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-json
      - id: pretty-format-json
        args: [--autofix]
      - id: check-xml
      - id: debug-statements
      - id: check-added-large-files
      - id: check-case-conflict
      - id: requirements-txt-fixer
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [--line-length=120]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: [
          "--max-line-length=120",
          "--ignore=E111,E114,E121,E131,W503,F405,F403,E126,E501,F841,E722,E741,E226"
        ]

  - repo: https://github.com/resmio/pre-commit-doctoc
    rev: v1.0.0
    hooks:
      - id: doctoc
        args: [--title=## Table of Contents]

default_language_version:
  python: python3

fail_fast: true
exclude: (migrations)
